"""empty message

Revision ID: 5e541804f336
Revises: 0bdda0ebc72b
Create Date: 2024-03-25 18:56:15.741284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e541804f336'
down_revision: Union[str, None] = '0bdda0ebc72b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('day_results', sa.Column('date', sa.String(), nullable=False))
    op.add_column('day_results', sa.Column('norma', sa.Integer(), nullable=False))
    op.add_column('day_results', sa.Column('get_in_day', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('day_results', 'get_in_day')
    op.drop_column('day_results', 'norma')
    op.drop_column('day_results', 'date')
    # ### end Alembic commands ###
